### ISSUE TITLE
Failed Normalization of BOLD

### ISSUE THREAD

**Issue by ly6ustc** [nipreps/fmriprep#2410] opened 2021-05-14 09:33 UTC
### What version of fMRIPrep are you using?
20.1.1
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Docker
### What is the exact command-line you used?
```docker run -i --name fmriprep$name --rm \
			-v $fs_licence:/opt/freesurfer/license.txt:ro \
			-v $BIDSdir:/data:ro \
                        -v /home/z/Data/Toolbox/templateflow:/home/fmriprep/.cache/templateflow \
			-v $prepre_dir:/out \
			-v $work_dir/work:/scratch \
			poldracklab/fmriprep:latest \
			/data /out \
			participant --participant-label $name \
			-w /scratch \
			--use-aroma \
			--nthreads $nthreads \
		 	--output-spaces $out_space \
                        --cifti-output
<place your command line here>
```

### Have you checked that your inputs are BIDS valid?
Yes,  bids/validator
### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
![image](https://user-images.githubusercontent.com/69618541/118237502-f2364080-b4c9-11eb-8251-5fe290234acc.png)
![image](https://user-images.githubusercontent.com/69618541/118237744-2f023780-b4ca-11eb-9133-4f5d7db7e8f6.png)
![image](https://user-images.githubusercontent.com/69618541/118237817-40e3da80-b4ca-11eb-9c05-d216d27e3b14.png)
![image](https://user-images.githubusercontent.com/69618541/118237876-578a3180-b4ca-11eb-8e4a-16adff575a38.png)

### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
No errors.
<please copy&paste all the information you can gather about errors>
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
No

### fMRIPrep log
If you have access to the output logged by fMRIPrep, please make sure to attach it as a text file to this issue.

[fmriprep.toml.txt](https://github.com/nipreps/fmriprep/files/6477314/fmriprep.toml.txt)

Dear nipreps-team,

I found some failed normalization of BOLD, similar to #2307 and #2393 . Specifically, as we seen, I think this subject's  visual report is fine, but generating  poor MNI normalizations for the functional images (see images below, including MNI152NLin6Asym_res-2 (left) and MNI152NLin2009cAsym(right) spaces)
![image](https://user-images.githubusercontent.com/69618541/118242080-80f98c00-b4cf-11eb-88d3-42328b8c2e71.png)
And it seems that a little better when I use "--fs-no-reconall", as seen in figure below. But if I want the results based on surface, what should I do?
![image](https://user-images.githubusercontent.com/69618541/118248403-d2f1e000-b4d6-11eb-9591-554025166999.png)

According to prior answers (#2307 and #2393), it appears that there is no good solution for this question.
But is there a way to check if the generated results have been affected by this bug other than by visual examination of the MNI normalization (actually, HTML visual reports usually look normal for these faild normalization)?  I'm afraid that some images had been affected by this bug but they were not readily noticeable (e.g., figure below).
![image](https://user-images.githubusercontent.com/69618541/118247773-27489000-b4d6-11eb-9210-7c6ebfd34aac.png)

Another question is that does this bug will affect surface space? e.g., fsaverage6, fsaverage5, or cifti-91k?
I don't know how to check surface results.  As shown in figure below, does it will result in vertexs with small value (red boxes)?

![image](https://user-images.githubusercontent.com/69618541/118250912-8e1b7880-b4d9-11eb-8519-12a915bbee75.png)

Thank a lot!

**Comment by yushiangsu** [comment] 2021-07-14 10:47
We have similar problem. This is not just happened in one or two subjects. It happened on most of our samples. Perhaps our case might help to diagnose this problem.

Our bold images have two scanning procedure. One is scanning along AC-PC line, the other is with scanning axis tilting up 30 degree up AC-PC line to lessen signal dropouts in orbitofrontal regions. After fmriprep preprocessing (latest version 20.2.1), the image followed AC-PC line perfectly match to normalized T1w images. But all images with tilting scanning axis showed some stretches on images.

This is how it looks for these two images.
<img width="774" alt="bold" src="https://user-images.githubusercontent.com/17156190/125606500-1f2f398e-8bc2-4163-936a-dfe4c57b101f.png">
<img width="774" alt="task" src="https://user-images.githubusercontent.com/17156190/125606504-c08eaaf9-c473-49f4-b04f-ed0bea9fe475.png">

<img width="1577" alt="screenshot1" src="https://user-images.githubusercontent.com/17156190/125606535-0b9b0ffe-9449-4915-96d1-620344157fc7.png">
<img width="1577" alt="screenshot2" src="https://user-images.githubusercontent.com/17156190/125606561-44ed3dac-078e-4786-8211-1b9704547cc0.png">

This animation might give a better visualization on the stretches.
![gifbold](https://user-images.githubusercontent.com/17156190/125609332-e3203400-b007-4453-b827-3dc23daa3ce7.gif)

We try fmriprep options like `--force-bbr`, `--force-no-bbr`, `--bold2t1w-init`, `--bold2t1w-dof`. These options have no help. But option `--fs-no-recomall` do the help, and generate bold images well matched to normalized T1w images. As previous comments suggest, we also try fmriprep with older verision `20.0.6` and generated perfectly matched bold images as well. 
We also checked the intermediate images by looking inside temporary work directories. The bold images that register to t1w match perfectly. But have no idea how there is the problem when resampling bold to standard space including transformations parameter generate by `bbregister`. But `flirt` (by testing 20.0.6 and --fs-no-reconall) have no problem. 

Thanks for digging in this problem.

**Comment by yushiangsu** [comment] 2021-07-18 03:49
The problem is solved with recent updated version (20.2.2).
![before](https://user-images.githubusercontent.com/17156190/126055017-1f35820d-7eb8-4b7e-bb53-19d78d7eb218.png)
![after](https://user-images.githubusercontent.com/17156190/126055021-5603bb8a-9386-43d6-8781-e1f91c8c2365.png)

**Comment by ly6ustc** [comment] 2021-07-18 05:58
> The problem is solved with recent updated version (20.2.2).
> ![before](https://user-images.githubusercontent.com/17156190/126055017-1f35820d-7eb8-4b7e-bb53-19d78d7eb218.png)
> ![after](https://user-images.githubusercontent.com/17156190/126055021-5603bb8a-9386-43d6-8781-e1f91c8c2365.png)

Thanks, help a lot!

**Comment by oesteban** [comment] 2021-07-18 07:32
It seems this was a duplicate of #2393 and solved with #2444 - is that right?

**Comment by ly6ustc** [comment] 2021-07-18 08:49
> It seems this was a duplicate of #2307 & #2393 and solved with #2444 - is that right?

Yes, I think they are the same problems.  
And I will reprocess the failed subjects using 20.2.2 version, or should I reprocess all subjects? 
I think I could use Freesurfer's results of 20.1.1 version(using parameter "--fs-subjects-dir") rather than do the Freesurfer's program using 20.2.2 version again, is it right?

**Comment by oesteban** [comment] 2021-07-18 19:56
> I think I could use Freesurfer's results of 20.1.1 version(using parameter "--fs-subjects-dir") rather than do the Freesurfer's program using 20.2.2 version again, is it right?

This is okay as long as the freesurfer version is constant. If you're using our docker images (or singularity images generated from them), both will indeed have the same FS version inside.

**Comment by oesteban** [comment] 2021-07-19 07:08
Thanks for reporting and then following up - it's been very helpful @ly6ustc.

Let's continue conversations in #2451 and #2452.

Please reopen if required.

**Closed by oesteban** 2021-07-19 07:08 UTC
Labels: bug

**Comment by ly6ustc** [comment] 2021-07-19 07:24
> Thanks for reporting and then following up - it's been very helpful @ly6ustc.
> 
> Let's continue conversations in #2451 and #2452.
> 
> Please reopen if required.

Thanks！
