### ISSUE TITLE
Phasediff field maps problem with V23.0.2

### ISSUE THREAD

**Issue by manzouri** [nipreps/fmriprep#2999] opened 2023-04-27 19:57 UTC
### What happened?

I used phasediff field maps from Siemens including 2 magnitude images and one phasediff with V20.2.7 and it works perfectly fine. But now when I run it with the latest version (23.0.2) I get different results where the correction stretch the image and doesn't look correct. I saw another post that you recommended to skull strip the phasediff ,which I did but still the result look stretched and different from V20.2.7.

### What command did you use?

```shell
fmriprep-docker $bids_root_dir $out_dir/ \
    participant \
    --participant-label $subject \
    --skip-bids-validation \
    --md-only-boilerplate \
    --output-spaces MNI152NLin2009cAsym \
    --no-tty \
    --nthreads $nthreads \
    --stop-on-first-crash \
    --mem_mb $mem_mb \
    -w $wd_dir \
    --fs-license-file /home/common/toolbox/license/license_freesurfer_oct22.txt \
    --notrack
```

### What version of fMRIPrep are you running?

23.0.2

### How are you running fMRIPrep?

Docker

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
No
```

**Comment by effigies** [comment] 2023-10-04 14:27
Duplicate of #3013.

**Closed by effigies** 2023-10-04 14:27 UTC
Labels: bug
