### ISSUE TITLE
FMRIPREP with longitudinal freesurfer pre-runs

### ISSUE THREAD

**Issue by dorianps** [nipreps/fmriprep#1919] opened 2019-12-24 23:20 UTC
Re-posting neurostar question here to get some quicker feedback.

We are getting ready for "production", that is, fire up fmriprep on a dataset of few thousand sessions. These are data with annual sessions from Huntington's disease patients (about 5 year follow ups). The anatomical changes are certainly there (i.e., 1-3% atrophy in the striatum) but the changes are not hugely remarkable.

I just tested fmriprep-1.5.4 with a (self created) singularity container, and seems to work well. Before we fire up the pipeline on all the dataset I wanted to clarify a few pending questions:

1. We have Freesurfer data on all these subjects (longitudinal pipeline). Looks like fmriprep cannot use those outputs, at least from posts from July 2019. Is this still the case?
2. If fmriprep cannot use (by default) FS longitudinal data, which option do you suggest to use:
* Let fmriprep create it's own "T1w average + freesurfer" output. My concern here is that BOLD data cannot be easily brought back to the T1w space of each individual session (the average of all sessions is in a different space). Are the the transformations to/from individual T1w sessions somewhere in the fmriprep output or working folder?
* Point fmriprep to the sst created by Freesurfer, which should be similar to what fmriprep creates itself (right?).
* Point fmriprep to use one of the processed Freesurfer sessions (either baseline or long folders).

Our Freesurfer data for a subject have this structure:
```
├── sst
├── sub-T2592_ses-01
├── sub-T2592_ses-01.long.sst
├── sub-T2592_ses-02
├── sub-T2592_ses-02.long.sst
├── sub-T2592_ses-03
├── sub-T2592_ses-03.long.sst
├── sub-T2592_ses-04
├── sub-T2592_ses-04.long.sst
├── sub-T2592_ses-05
├── sub-T2592_ses-05.long.sst
├── sub-T2592_ses-06
├── sub-T2592_ses-06.long.sst
├── sub-T2592_ses-07
└── sub-T2592_ses-07.long.sst
```

More generally, are you planning to enable the use of FS longitudinal outputs in the near future?

3. Finally, I noticed you are preparing for a new release soon. We don't mind waiting 1-2 months to process the data with a better version of fmriprep, but we are not sure whether the upcoming releases have major advantages worth waiting. Can you give us an idea about the plans for future releases?

Thank you for your help and for providing such a complex well developed pipeline to the community.

**Comment by dorianps** [comment] 2019-12-25 19:42
Another question:

We are working to build a study-specific template. If we add that template later in templateflow format, can we rerun fmriprep and have it produce only that new output space without running everything all the processes from scratch? Would fmriprep know to skip processing of existing outputs?

**Comment by effigies** [comment] 2022-12-03 02:01
Looks like this fell victim to a holiday break. Apologies, Dorian. This is a duplicate of https://github.com/nipreps/smriprep/issues/21.

**Closed by effigies** 2022-12-03 02:01 UTC
