### ISSUE TITLE
Strange pattern on distortion corrected images

### ISSUE THREAD

**Issue by jameswyngaarden** [nipreps/fmriprep#3093] opened 2023-09-25 22:12 UTC
### What happened?

We have multiband/multi-echo data that shows a strange pattern after going through distortion correction. This only occurs for our multiband = 6, multi-echo = 4 images (e.g., multiband = 1 multi-echo = 4 does not show this effect, neither does any other combination). The raw data looks normal as far as we can tell. The pattern does show some resemblance to the phase image--beyond this though we don’t really understand what’s happening here. This pattern appears when we use fieldmaps and when we use fieldmap-free distortion correction (e.g., `--ignore-fieldmaps` & `--use-syn-sdc` options). There are no error messages in the html report.  

For additional context, my lab's PI @DVSneuro recently posted a related issue here: https://github.com/nipreps/fmriprep/issues/3056#issuecomment-1685079650

### What command did you use?

```shell
singularity run --cleanenv \ 
		-B ${TEMPLATEFLOW_DIR}:/opt/templateflow \ 
		-B ${MPLCONFIGDIR_DIR}:/opt/mplconfigdir \ 
		-B $maindir:/base \ 
		-B ~/work/tools/licenses:/opts \ 
		-B $scratchdir:/scratch \ 
		~/work/tools/fmriprep-23.1.4.simg \ 
		/base/bids /base/derivatives/fmriprep \ 
		participant --participant_label $sub \ 
		--stop-on-first-crash \ 
		--nthreads 12 \ 
		--me-output-echos \ 
		--ignore fieldmaps \ 
		--use-syn-sdc \ 
		--cifti-output 91k \ 
		--output-spaces fsLR fsaverage MNI152NLin6Asym \ 
		--bids-filter-file /base/code/fmriprep_config.json \ 
		--fs-license-file /opts/fs_license.txt -w /scratch
```

### What version of fMRIPrep are you running?

23.1.4 

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
N/A
```

### Additional information / screenshots

Distorted image:
<img width="803" alt="Screenshot 2023-09-25 at 3 13 51 PM" src="https://github.com/nipreps/fmriprep/assets/68560550/76df793e-785e-4188-a82a-9245619e7ca6">

"Corrected" image:
<img width="804" alt="Screenshot 2023-09-25 at 3 14 02 PM" src="https://github.com/nipreps/fmriprep/assets/68560550/a7af67c3-a1cc-488d-9c66-64c33ae3db18">

Phase image:
<img width="705" alt="Screenshot 2023-09-25 at 2 55 36 PM" src="https://github.com/nipreps/fmriprep/assets/68560550/ce9cf8f8-5ee6-425a-95d3-7f28896b56fd">

**Comment by effigies** [comment] 2023-09-26 11:29
Duplicate of #3013. Please follow up there.

**Closed by effigies** 2023-09-26 11:29 UTC
Labels: bug
