### ISSUE TITLE
syn-sdc not working with multiple sessions

### ISSUE THREAD

**Issue by dlinhardt** [nipreps/fmriprep#2695] opened 2022-01-21 13:09 UTC
### What happened?

When trying to run a subjects containing two sessions with the option` --use-syn-sdc` for distortion correction fMRIPrep crashes when using 21.0.0. When processing single-session subjects everything works, also when using 20.2.6.

### What command did you use?

```shell
unset PYTHONPATH; singularity run \
	-H $home_dir \
	-B $bids_root_dir:/base -B $FS_LICENSE:/license \
	--cleanenv /path/fmriprep-21.0.0.sif \
	/base/BIDS /base/derivatives participant \
	--participant-label $subj \
	--skip-bids-validation \
	--output-spaces func fsnative fsaverage T1w MNI152NLin2009cAsym \
	--dummy-scans 0 \
	--use-syn-sdc \
	--force-no-bbr \
	--fs-license-file /license/license.txt \
	-w /base/derivatives \
	--nthreads $nthreads \
	--omp-nthreads $nthreads \
	--stop-on-first-crash \
	--mem_mb $mem_mb \
	--output-layout legacy \
	--anat-derivatives /base/derivatives/fmriprep
```

### What version of fMRIPrep are you running?

21.0.0

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

No

### Are you reusing any previously computed results?

FreeSurfer

### Please copy and paste any relevant log output.

```shell
220121-13:57:01,198 nipype.workflow INFO:
         Setting-up fieldmap "auto_00000" (EstimatorType.ANAT) with <sub-004_ses-1_T1w.nii.gz, sub-004_ses-1_task-automem_run-01_bold.nii.gz, sub-004_ses-1_task-nback_run-01_bold.nii.gz, sub-004_ses-1_task-rsclose_run-01_bold.nii.gz, sub-004_ses-1_task-rsopen_run-01_bold.nii.gz>
220121-13:57:01,236 nipype.workflow INFO:
         Setting-up fieldmap "auto_00001" (EstimatorType.ANAT) with <sub-004_ses-1_T1w.nii.gz, sub-004_ses-2_task-automem_run-01_bold.nii.gz, sub-004_ses-2_task-nback_run-01_bold.nii.gz, sub-004_ses-2_task-rsclose_run-01_bold.nii.gz, sub-004_ses-2_task-rsopen_run-01_bold.nii.gz>
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/opt/conda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 480, in init_single_subject_wf
    workflow.connect([
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 161, in connect
    self._check_nodes(newnodes)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 769, in _check_nodes
    raise IOError('Duplicate node name "%s" found.' % node.name)
OSError: Duplicate node name "fmap_select_std" found.
```

**Comment by effigies** [comment] 2022-01-21 13:59
This will be fixed in 21.0.1, likely out next week.

Duplicate of #2687.

**Closed by effigies** 2022-01-21 13:59 UTC
Labels: bug
