### ISSUE TITLE
topup post-processing failure on 21.0.0RC2

### ISSUE THREAD

**Issue by Lestropie** [nipreps/fmriprep#2641] opened 2021-11-29 01:34 UTC
### What happened?

First test of 21.0.0RC2 on data that has proven problematic thus far (combined multi-echo fMRI and spin-echo EPIs for susceptibility field estimation, which was non-functional in RC0: #2558). `topup` executes successfully, but subsequent "`fix_coeff` function throws an unhandled Exception.

### What command did you use?

```shell
singularity run --cleanenv \
    --bind /projects/hb93:/projects/hb93,/scratch/hb93:/scratch/hb93 \
    /scratch/hb93/fmriprep-21.0.0rc2.sif /scratch/hb93/rob_testing_fmri/BIDS /scratch/hb93/rob_testing_fmri/rc2 participant \
    --participant_label sub-01 \
    --nthreads 4 --omp-nthreads 4 --mem_mb 16384 \
    --output-spaces T1w MNI152NLin6Asym:res-2 fsaverage5 \
    --fs-license-file /projects/hb93/freesurfer_license.txt \
    --fs-subjects-dir /scratch/hb93/rob_testing_fmri/freesurfer \
    -w /scratch/hb93/rob_testing_fmri/work
```

### What version of fMRIPrep are you running?

21.0.0RC2

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

### Please copy and paste any relevant log output.

```shell
211123-13:51:16,697 nipype.workflow WARNING:
	 [Node] Error on "fmriprep_wf.single_subject_01_wf.fmap_preproc_wf.wf_auto_00000.fix_coeff" (/scratch/hb93/rob_testing_fmri/work/fmriprep_wf/single_subject_01_wf/fmap_preproc_wf/wf_auto_00000/fix_coeff)
211123-13:51:16,779 nipype.workflow ERROR:
	 Node fix_coeff failed to run on host m3i037.
211123-13:51:16,792 nipype.workflow ERROR:
	 Saving crash info to /scratch/hb93/rob_testing_fmri/rc2/sub-01/log/20211123-130706_d88ce07e-b99b-4ca1-b83e-037638e6872b/crash-20211123-135116-robertes-fix_coeff-5bdb8b27-2b61-4223-9b25-5be1f020e564.txt
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/plugins/multiproc.py", line 344, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/opt/conda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/opt/conda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/interfaces/bspline.py", line 420, in _run_interface
    self._results["out_coeff"] = [
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/interfaces/bspline.py", line 422, in <listcomp>
    _fix_topup_fieldcoeff(
  File "/opt/conda/lib/python3.8/site-packages/sdcflows/interfaces/bspline.py", line 480, in _fix_topup_fieldcoeff
    raise ValueError(
ValueError: Shape of coefficients file [72 72 44] does not meet the expectation given the reference's shape [72 72 44].
```
```


### Additional information / screenshots

_No response_

**Comment by oesteban** [comment] 2021-11-29 08:37
I think this is a duplicate of https://github.com/nipreps/fmriprep/issues/2628#issuecomment-975719689, and we are following up in nipreps/sdcflows#250.

We have pushed a Docker image including a patch to dockerhub (tag: ``nipreps/fmriprep:pepolar-2628``), just in case you could give it a try - please let us know if the patch is working.

To follow up on this bug, please head to the sdcflows issue linked in the first paragraph.

**Closed by oesteban** 2021-11-29 08:37 UTC
Labels: bug
