### ISSUE TITLE
citation from 23.0.1 contains a duplicate paragraph with one difference

### ISSUE THREAD

**Issue by burdinskid13** [nipreps/fmriprep#3218] opened 2024-02-01 06:50 UTC
### What happened?

I noticed when trying to copy the citation from version 23.0.1 that the paragraph labeled "Functional data preprocessing" is duplicated with one small difference: Paragraph 1 contains "BOLD runs were slice-time corrected to 0.721s (0.5 of slice acquisition range 0s-1.44s)" and paragraph 2 contains "BOLD runs were slice-time corrected to 0.722s (0.5 of slice acquisition range 0s-1.45s)" -- which is the correct paragraph? And am I allowed to delete a paragraph when I incorporate the whole citation into my paper, since I would be technically modifying what you request to copy as a whole? Thanks so much!

### What command did you use?

```shell
inspecting html reports after running fmriprep 23.0.1
```

### What version of fMRIPrep are you running?

23.0.1

### How are you running fMRIPrep?

Singularity

### Is your data BIDS valid?

Yes

### Are you reusing any previously computed results?

No

**Comment by effigies** [comment] 2024-02-01 18:09
> which is the correct paragraph?

I would guess that there was a very slight difference in the RepetitionTime metadata across runs. Because the text was not identical, it wasn't deduplicated.

I would select the one that matches your understanding of the data and delete the other. A 1ms difference should not substantially impact the results of processing, so I would not worry about adding qualifying text.

> And am I allowed to delete a paragraph when I incorporate the whole citation into my paper, since I would be technically modifying what you request to copy as a whole?

The point of the suggestion that people post it verbatim is because we have had people unnecessarily change text in order to avoid plagiarism detection software, so we wanted to stand behind users and make it clear that was our intention. (See [Copy-pasting your methods section is good, actually.](https://reproducibility.stanford.edu/copy-pasting-your-methods-section-is-good-actually/))

FWIW I think this is a very good reason for modifying the text, but I can't stress enough that you do not need our permission for anything. The text is released into the public domain and can be used verbatim or modified to any extent and for any reason.

**Comment by burdinskid13** [comment] 2024-02-01 18:19
Sounds great, thanks!

**Closed** 2024-02-01 18:19 UTC
Labels: bug
