### ISSUE TITLE
"np" not defined

### ISSUE THREAD

**Issue by smeisler** [nipreps/fmriprep#2544] opened 2021-09-15 19:54 UTC
### What version of fMRIPrep are you using?
21.0.0rc0
### What kind of installation are you using? Containers (Singularity, Docker), or "bare-metal"?
Singularity (3.6.3) on Linux HPC
### What is the exact command-line you used?
```
singularity run -B ${scratch} -B ${bids_dir} $IMG ${bids_dir} ${output_dir} participant --participant_label ${subject:4} \
-w $scratch --fs-license-file $license --ignore fieldmaps --mem_mb 39500 --use-syn-sdc --force-syn \
--skip-bids-validation --use-aroma --cifti-output 91k \
--output-spaces MNIPediatricAsym:cohort-1 T1w MNI152NLin6Asym MNI152NLin2009cAsym
```

### Have you checked that your inputs are BIDS valid?
Yes ([OpenNeuro ds003604](https://openneuro.org/datasets/ds003604/versions/1.0.2))
### Did fMRIPrep generate the visual report for this particular subject? If yes, could you share it?
No
### Can you find some traces of the error reported in the visual report (at the bottom) or in *crashfiles*?
```
210915-15:36:23,976 nipype.workflow IMPORTANT:
	 Building fMRIPrep's workflow:
           * BIDS dataset path: /om4/group/gablab/data/ds003604.
           * Participant list: ['5002'].
           * Run identifier: 20210915-151951_359f75f4-363f-4879-a91f-dc4319eb776d.
           * Output spaces: MNIPediatricAsym:cohort-1:res-native T1w MNI152NLin6Asym:res-native MNI152NLin2009cAsym:res-native.
           * Pre-run FreeSurfer's SUBJECTS_DIR: /om4/group/gablab/data/ds003604/derivatives/freesurfer.
210915-15:36:29,480 nipype.workflow CRITICAL:
	 SyN processing is not yet implemented.
210915-15:36:29,759 nipype.workflow INFO:
	 No single-band-reference found for sub-5002_ses-5_task-Gram_acq-D1S11_run-01_bold.nii.gz.
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/miniconda/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/cli/workflow.py", line 118, in build_workflow
    retval["workflow"] = init_fmriprep_wf()
  File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 85, in init_fmriprep_wf
    single_subject_wf = init_single_subject_wf(subject_id)
  File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/workflows/base.py", line 349, in init_single_subject_wf
    func_preproc_wf = init_func_preproc_wf(bold_file, has_fieldmap=has_fieldmap)
  File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/workflows/bold/base.py", line 446, in init_func_preproc_wf
    bold_stc_wf = init_bold_stc_wf(name='bold_stc_wf', metadata=metadata)
  File "/usr/local/miniconda/lib/python3.8/site-packages/fmriprep/workflows/bold/stc.py", line 99, in init_bold_stc_wf
    tzero = np.round(first + frac * (last - first), 3)
NameError: name 'np' is not defined
```

### Are you reusing previously computed results (e.g., FreeSurfer, Anatomical derivatives, work directory of previous run)?
Yes (previous recon-all outputs)

### fMRIPrep log
Included in the traceback

**Comment by effigies** [comment] 2021-09-15 20:10
Duplicate of #2532. Fixed in #2533. We plan to release another RC in the next day or two. In the meantime, you can use `nipreps/fmriprep:unstable`.

**Closed by effigies** 2021-09-15 20:10 UTC
Labels: bug
