### ISSUE TITLE
/opt/freesurfer/bin/mri_convert: line 3: 26595 Segmentation fault      mri_convert.bin "$@" ERROR: converting to minc

### ISSUE THREAD

**Issue by BlackHoleExelion** [nipreps/fmriprep#2518] opened 2021-08-26 14:19 UTC
Hello,

I am using fmriprep singularity container v20.2.3 on HPC. It crashed during freesurfer recon-all processing. 
Specifically, `mri_convert orig.mgz ./tmp.mri_nu_correct.mni.24354/nu0.mnc -odt float` failed with error `/opt/freesurfer/bin/mri_convert: line 3: 24389 Segmentation fault      mri_convert.bin "$@"
ERROR: converting to minc`

I tried to manually run it inside the container (singularity shell) and got the same error.
The weird thing is that it worked fine with no error when I ran it with freesurfer7.1.1 installed on the HPC.

The full freesurfer log has been attached as below:

```
===========================================
Node: fmriprep_wf.single_subject_C103_wf.anat_preproc_wf.surface_recon_wf.autorecon1
Working directory: /mnt/fmriprep/temp_fmriprep/fmriprep_wf/single_subject_C103_wf/anat_preproc_wf/surface_recon_wf/autorecon1

Node inputs:

FLAIR_file = <undefined>
T1_files = <undefined>
T2_file = <undefined>
args = <undefined>
big_ventricles = <undefined>
brainstem = <undefined>
directive = autorecon1
environ = {}
expert = <undefined>
flags = <undefined>
hemi = <undefined>
hippocampal_subfields_T1 = <undefined>
hippocampal_subfields_T2 = <undefined>
hires = <undefined>
mprage = <undefined>
mri_aparc2aseg = <undefined>
mri_ca_label = <undefined>
mri_ca_normalize = <undefined>
mri_ca_register = <undefined>
mri_edit_wm_with_aseg = <undefined>
mri_em_register = <undefined>
mri_fill = <undefined>
mri_mask = <undefined>
mri_normalize = <undefined>
mri_pretess = <undefined>
mri_remove_neck = <undefined>
mri_segment = <undefined>
mri_segstats = <undefined>
mri_tessellate = <undefined>
mri_watershed = <undefined>
mris_anatomical_stats = <undefined>
mris_ca_label = <undefined>
mris_fix_topology = <undefined>
mris_inflate = <undefined>
mris_make_surfaces = <undefined>
mris_register = <undefined>
mris_smooth = <undefined>
mris_sphere = <undefined>
mris_surf2vol = <undefined>
mrisp_paint = <undefined>
openmp = 8
parallel = <undefined>
steps = <undefined>
subject_id = recon_all
subjects_dir = <undefined>
talairach = <undefined>
use_FLAIR = <undefined>
use_T2 = <undefined>
xopts = <undefined>

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/plugins/multiproc.py", line 67, in run_node
    result["result"] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 516, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 635, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/pipeline/engine/nodes.py", line 741, in _run_command
    result = self._interface.run(cwd=outdir)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 428, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 822, in _run_interface
    self.raise_exception(runtime)
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 753, in raise_exception
    ).format(**runtime.dictcopy())
RuntimeError: Command:
recon-all -autorecon1 -i /mnt/BIDS/ZAPR01/C103/sub-C103/ses-Baseline/anat/sub-C103_ses-Baseline_acq-MPR_T1w.nii.gz -noskullstrip -cw256 -hires -openmp 8 -subjid sub-C103 -sd /mnt/fmriprep/output/freesurfer -expert /mnt/fmriprep/temp_fmriprep/fmriprep_wf/single_subject_C103_wf/anat_preproc_wf/surface_recon_wf/autorecon1/expert.opts
Standard output:
INFO: hi-res volumes are conformed to the min voxel size
Subject Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
Current Stamp: freesurfer-Linux-centos6_x86_64-stable-pub-v6.0.1-f53a55a
INFO: SUBJECTS_DIR is /mnt/fmriprep/output/freesurfer
Actual FREESURFER_HOME /opt/freesurfer
Linux singularity01 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
'/opt/freesurfer/bin/recon-all' -> '/mnt/fmriprep/output/freesurfer/sub-C103/scripts/recon-all.local-copy'
-cw256 option is now persistent (remove with -clean-cw256)
/mnt/fmriprep/output/freesurfer/sub-C103

 mri_convert /mnt/BIDS/ZAPR01/C103/sub-C103/ses-Baseline/anat/sub-C103_ses-Baseline_acq-MPR_T1w.nii.gz /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig/001.mgz 

mri_convert.bin /mnt/BIDS/ZAPR01/C103/sub-C103/ses-Baseline/anat/sub-C103_ses-Baseline_acq-MPR_T1w.nii.gz /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig/001.mgz 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /mnt/BIDS/ZAPR01/C103/sub-C103/ses-Baseline/anat/sub-C103_ses-Baseline_acq-MPR_T1w.nii.gz...
TR=2400.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (1, 0, 0)
j_ras = (0, 1, 0)
k_ras = (0, 0, 1)
writing to /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig/001.mgz...
#--------------------------------------------
#@# MotionCor Thu Aug 26 09:33:41 EDT 2021
Found 1 runs
/mnt/fmriprep/output/freesurfer/sub-C103/mri/orig/001.mgz
Checking for (invalid) multi-frame inputs...
WARNING: only one run found. This is OK, but motion
correction cannot be performed on one run, so I'll
copy the run to rawavg and continue.

 cp /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig/001.mgz /mnt/fmriprep/output/freesurfer/sub-C103/mri/rawavg.mgz 

/mnt/fmriprep/output/freesurfer/sub-C103

 mri_convert /mnt/fmriprep/output/freesurfer/sub-C103/mri/rawavg.mgz /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig.mgz --conform_min 

mri_convert.bin /mnt/fmriprep/output/freesurfer/sub-C103/mri/rawavg.mgz /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig.mgz --conform_min 
$Id: mri_convert.c,v 1.226 2016/02/26 16:15:24 mreuter Exp $
reading from /mnt/fmriprep/output/freesurfer/sub-C103/mri/rawavg.mgz...
TR=2400.00, TE=0.00, TI=0.00, flip angle=0.00
i_ras = (1, 0, 0)
j_ras = (0, 1, 0)
k_ras = (0, 0, 1)
changing data type from float to uchar (noscale = 0)...
MRIchangeType: Building histogram 
Reslicing using trilinear interpolation 
writing to /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig.mgz...

 mri_add_xform_to_header -c /mnt/fmriprep/output/freesurfer/sub-C103/mri/transforms/talairach.xfm /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig.mgz /mnt/fmriprep/output/freesurfer/sub-C103/mri/orig.mgz 

INFO: extension is mgz
#--------------------------------------------
#@# Talairach Thu Aug 26 09:33:58 EDT 2021
/mnt/fmriprep/output/freesurfer/sub-C103/mri

 mri_nu_correct.mni --no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50 

/mnt/fmriprep/output/freesurfer/sub-C103/mri
/opt/freesurfer/bin/mri_nu_correct.mni
--no-rescale --i orig.mgz --o orig_nu.mgz --n 1 --proto-iters 1000 --distance 50
nIters 1
$Id: mri_nu_correct.mni,v 1.27 2016/02/26 16:19:49 mreuter Exp $
Linux singularity01 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Thu Aug 26 09:33:58 EDT 2021
Program nu_correct, built from:
Package MNI N3, version 1.12.0, compiled by nicks@terrier (x86_64-unknown-linux-gnu) on 2015-06-19 at 01:25:34
/usr/bin/bc
tmpdir is ./tmp.mri_nu_correct.mni.24354
/mnt/fmriprep/output/freesurfer/sub-C103/mri
mri_convert orig.mgz ./tmp.mri_nu_correct.mni.24354/nu0.mnc -odt float
mri_convert.bin orig.mgz ./tmp.mri_nu_correct.mni.24354/nu0.mnc -odt float 
/opt/freesurfer/bin/mri_convert: line 3: 24389 Segmentation fault      mri_convert.bin "$@"
ERROR: converting to minc
Linux singularity01 3.10.0-1127.8.2.el7.x86_64 #1 SMP Tue May 12 16:57:42 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

recon-all -s sub-C103 exited with ERRORS at Thu Aug 26 09:34:00 EDT 2021

For more details, see the log file /mnt/fmriprep/output/freesurfer/sub-C103/scripts/recon-all.log
To report a problem, see http://surfer.nmr.mgh.harvard.edu/fswiki/BugReporting

Standard error:

Return code: 1
```

**Comment by effigies** [comment] 2023-10-19 12:01
Duplicate of https://github.com/nipreps/smriprep/issues/123. Please follow up there.

If you're able to share a failing T1w image, we can try to replicate the issue.

**Closed by effigies** 2023-10-19 12:01 UTC
Labels: question
