### ISSUE TITLE
Visual reports: are they really self-contained?

### ISSUE THREAD

**Issue by jflournoy** [nipreps/fmriprep#2334] opened 2020-11-20 21:45 UTC
Currently, under the description of visual reports, [the docs](https://github.com/nipreps/fmriprep/blob/0dba10208e5361bc94cdc5334826afa64d0617a1/docs/outputs.rst#visual-reports) state:

> Each report is self contained and thus can be easily shared with collaborators (for example via email)

However, when I copy an html file to my local computer from, say, a cluster, the images break because they are pointing to, e.g., `sub-101001/figures/sub-101001_dseg.svg`. I'm looking at output from fmriprep 20.1.1, and it doesn't look like anything relevant has changed since then. Is this my mistake or should the documentation be amended to clarify that the reports are only partially self-contained?

**Comment by effigies** [comment] 2020-11-20 21:58
They were self-contained, but for some reason browsers that are perfectly happy to fetch and display all of the same contents got really slow if the contents were embedded.

We should definitely amend the docs (I thought we already had...). Thanks for bringing it up.

**Comment by tsalo** [comment] 2023-12-06 20:10
Fixed by #2697. Also it's a duplicate of #995.

**Closed by tsalo** 2023-12-06 20:10 UTC
Labels: documentation
